# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94a1a236883e64641043b58dd0faa696c67e02581694d5096a2fd760c99285d35d47cc627b01975f1fb4307cbd71b37892f4bdb4e949bc1879e820b1036c20e3

test:
  secret_key_base: 720e81f870ebdcd771cd09879691d756b86217c25269d6e9659ae537940da2b0b8600aa2e68bfde95f883be4a58ae1c3883e5229422c23d38a582cfc14d9f121

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
